services:
  ecommerce-app:
    build:
      context: ./frontend-ecommerce
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend-ecommerce:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # RECTIFICATION : Le navigateur doit pointer sur le port HÔTE de votre backend PHP
      - VITE_API_URL=http://localhost:8080 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cekema_network  

 
networks:
  cekema_network:
    external: true