services:
  ecommerce-app:
    build:
      context: ./frontend-ecommerce
      dockerfile: Dockerfile.dev
      network: host # <-- Force l'utilisation de ta connexion directe pour le build
    ports:
      - "3000:5173"
    volumes:
      - ./frontend-ecommerce:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_API_URL=http://host.docker.internal:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elearning-app:
    build:
      context: ./frontend-elearning
      dockerfile: Dockerfile.dev
      network: host # <-- Idem ici
    ports:
      - "4000:5173"
    volumes:
      - ./frontend-elearning:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
      - VITE_API_URL=http://localhost:5715
    extra_hosts:
      - "host.docker.internal:host-gateway"